# example data report config file
map_version = "2301"
region = "sf"  # refer to keys in regions.json
date_start = "2023-03-01"  # YYYY-MM-DD
date_end = "2023-03-31"  # YYYY-MM-DD
granularity = 1  # minutes